server:
  port: 8886
spring:
  application:
    name: EDU-VIDEO
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

aliyun:
  oss:
    file:
      accessKeyId: LTAI4GJUXkVyr1abdhxoqiwX
      accessKeySecret: InS0bT9nCWwh7sSecFz0ewj70xz1J3

