server:
  port: 8888
spring:
  application:
    name: EDU-SERVICE

  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: user
    password: Songwenqu123,
    url: jdbc:p6spy:mysql://182.92.241.248:3306/guli?serverTimezone=GMT%2B8
#   url: jdbc:mysql://182.92.241.248:3306/guli?serverTimezone=GMT%2B8

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 设置开发环境
  profiles:
    active: dev

# 输出执行的sql语句
mybatis-plus:
  mapper-locations: classpath:com/song/eduservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

