server:
  port: 8887
spring:
  application:
    name: EDU-OSS
  profiles:
    active: dev

# \u963F\u91CC\u4E91oss\u7684\u914D\u7F6E
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI4GJUXkVyr1abdhxoqiwX
      accessKeySecret: InS0bT9nCWwh7sSecFz0ewj70xz1J3
      bucketname: edu-song-guli
